### ISSUE TITLE
Inverter Status: unknown type 7.5

### ISSUE THREAD

**Issue by mp21-org** [svalouch/rctmon#13]
I got a strange type (7.5) for inverter status. Any idea what this could mean?

![image](https://user-images.githubusercontent.com/1374810/132225286-066d9508-5ecc-4b9a-b0a6-0fb6c407cdaf.png)

**Comment by svalouch** [comment]
Looks like I made a copy&paste-error when assembling the documentation (assuming you're using the query from the `Flux queries` page), Sorry for that!

This is fixed by replacing `fn: mean` with `fn: max` in the `aggregateWindow`-function.

**Comment by mp21-org** [comment]
Thanks that was probably the cause of my problem. :-)
