### ISSUE TITLE
rctmon_generator_power_watt only returns string a

### ISSUE THREAD

**Issue by MichaelMMS** [svalouch/rctmon#2]
rctmon_generator_power_watt

Output:

rctmon_generator_power_watt{generator="a", instance="localhost:9831", inverter="PS 10.0 P1WF", job="rctmon"}

b is missing.
<img width="1249" alt="Bildschirmfoto 2021-07-08 um 12 30 30" src="https://user-images.githubusercontent.com/87091254/124907334-50723200-dfe8-11eb-8a0e-6c1d25e64e6f.png">

**Comment by MichaelMMS** [comment]
I fixed it, see pull request - oid was wrong

**Comment by svalouch** [comment]
Merged #5, thanks!
