### ISSUE TITLE
Unaligned data used for the same metric

### ISSUE THREAD

**Issue by sfudeus** [svalouch/rctmon#24]
During an island mode test I noticed that the exporter currently reads different values and uses the same prometheus metric for them. 
There are the `PowerSwitchReadings` (`rb485.*`), which generate `rctmon_grid_voltage` and `rctmon_grid_frequency`, and there are the `GridReading` (from `g_sync`), which create `rctmon_grid_voltage` and a single `rctmon_grid_frequency` (from `grid_pll`) without phase label. 
During island mode, they produce different readings (rb485 being low obviously, g_sync having the values created by the inverter. 
They should be handled differently. 

I'm willing to implement this, but I'd like to check how we want to name them. 
`rctmon_grid_*` suggests grid values, so ideally the rb485 ones, but what about people without a power switch?

I'm lacking a proper term for the g_sync values - they are about the inverter-generated, potentially grid-separated network, but household doesn't fit as well, since this a term referring to consumption from the household. 
Easiest might be to just rename the rb485 metrics `rctmon_powerswitch_*`, despite being metrics about the "real", i.e. external, grid. 

What is your opinion? 

PS: Any idea about the relevance of the `rctmon_powerstorage_frequency` metrics? They seem to be 0 for me all the time, regardless if in island mode or not.

**Comment by sfudeus** [comment]
While looking into it, there was only one really straightforward way without changing a lot more. See PR #25.

**Comment by MichaelMMS** [comment]
hi [sfudeus](https://github.com/sfudeus)
In island mode, I'll get a rctmon_grid_frequency reading of around 30 Hz. This is obviously wrong.
It should be 0 Hz. 

It is perhaps best to make it backwards compatible with your idea of "real, i.e. external, grid." with new variables and an explanation in the docs. I use grafana, I don't have any problems with wrong readings. Maybe you could do a screenshot of your wrong readings... 
<img width="1206" alt="Bildschirmfoto 2022-08-04 um 23 23 32" src="https://user-images.githubusercontent.com/87091254/182955343-74b4f41a-761c-4ce0-909c-0e0928c745ec.png">

<img width="1224" alt="Bildschirmfoto 2022-08-04 um 23 19 59" src="https://user-images.githubusercontent.com/87091254/182954859-765768bb-b6a2-4e93-94a3-b1fbc5c548db.png">
<img width="1224" alt="Bildschirmfoto 2022-08-04 um 23 19 52" src="https://user-images.githubusercontent.com/87091254/182954871-9f63ef16-8138-4632-8d93-41dbf3d20e0c.png">
<img width="1227" alt="Bildschirmfoto 2022-08-04 um 23 19 44" src="https://user-images.githubusercontent.com/87091254/182954878-4a8d20d0-fafa-4e4c-99e5-bd792a0e316a.png">
